## Atelier Numpy

### Contexte 
Une entreprise dispose de plusieurs capteurs installés dans différents bâtiments. Les capteurs 
mesurent régulièrement la température, l'humidité, la pression et la consommation énergétique. 
Les données doivent être préparées et analysées avant d'être transmises à un futur système de 
Machine Learning permettant de détecter des situations anormales 

### Partie 1 : Listes Python vs tableaux NumPy 

On dispose des températures mesurées par un capteur : 24.5, 25.1, 26.3, 27.0 et 25.8 

#### 1) Créer une liste Python stockant ces températures

In [2]:
tprt = [24.5, 25.1, 26.3, 27.0, 25.8]

#### 2) Création d'un tableau NumPy équivalent stockant ces températures

In [3]:
# Importation de la bibliothèque NumPy
import numpy as np

In [4]:
tprt_array = np.array([24.5, 25.1, 26.3, 27.0, 25.8])

#### 3) Multiplication par 2 sur ces deux collections

In [5]:
# Multiplication de chaque élément de la liste par 2
mul_tprt_list = [temp * 2 for temp in tprt]
mul_tprt_list

[49.0, 50.2, 52.6, 54.0, 51.6]

In [6]:
# Multiplication de chaque élément du tableau NumPy par 2
mul_tprt_array = tprt_array * 2
mul_tprt_array

array([49. , 50.2, 52.6, 54. , 51.6])

#### 4) Différence observée ?

On remarque que le liste python 'tprt' utilise une boucle 'for' en multipliant chaque élément de la liste pour pouvoir
avoir le résulat de la multiplication par 2 des températures stockés. Par contre le vecteur Numpy 'tprt_array' multiplie directement et simultanément tous éléments par 2 (technique du 'broadcasting') sans passer par une boucle. Ce qui énorme un terme de gain de temps 

### Partie 2 – Création des données

#### 1) Création d'un tableau représentant les mesures de température de 10 capteurs, initialement à zéro.

In [7]:
temp_10 = np.zeros(10)
temp_10

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 2) Création d'un tableau contenant 10 valeurs égales à 1

In [8]:
temp_10_1 = np.ones(10)
temp_10_1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 3) Création d'un tableau de 10 valeurs initialisées à 25

In [9]:
temp_10_25 = np.full(10, 25)
temp_10_25

array([25, 25, 25, 25, 25, 25, 25, 25, 25, 25])

#### 4) Création une matrice identité de taille 5 × 5

In [10]:
temp_ident = np.eye(5)
temp_ident

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### 5) Création de 24 heures (de 0 à 23) de mesure d’une journée 

In [11]:
temp_24 = np.arange(24)
temp_24

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

#### 6) Création de 10 valeurs régulièrement réparties entre 20 °C et 30 °C 

In [12]:
temp10_20_30 = np.linspace(20, 30, 10)
temp10_20_30

array([20.        , 21.11111111, 22.22222222, 23.33333333, 24.44444444,
       25.55555556, 26.66666667, 27.77777778, 28.88888889, 30.        ])

#### 7) Création aléatoire de températures de 100 mesures, en rendant les résultats reproductibles

In [13]:
np.random.seed(0)  # Pour la reproductibilité
temp_random = np.random.uniform(-10.0, 45.0, 100).round(2)
temp_random

array([20.18, 29.34, 23.15, 19.97, 13.3 , 25.52, 14.07, 39.05, 43.  ,
       11.09, 33.54, 19.09, 21.24, 40.91, -6.09, -5.21, -8.89, 35.79,
       32.8 , 37.85, 43.82, 33.95, 15.38, 32.93, -3.49, 25.2 , -2.12,
       41.96, 18.7 , 12.81,  4.55, 32.58, 15.09, 21.26, -8.97, 23.97,
       23.67, 23.93, 41.91, 27.5 ,  9.77, 14.04, 28.37, -6.69, 26.67,
       26.89,  1.57, -2.91,  7.35, 10.  , 21.36, 14.12, 44.36, -4.39,
        1.49, -1.13, 25.92,  3.93, 15.65,  3.44, -1.26, -3.93, 26.1 ,
       -2.4 ,  0.81, 10.28, 35.15, -4.66, 36.09, -4.71, 43.71, 15.78,
       43.72, 23.27, 30.66, -7.84,  5.55, -3.39,  6.29, -3.47,  7.49,
       12.78, -6.47, 28.09, 21.16,  4.6 , 18.78, -4.83, 21.68, 41.11,
        7.52, 26.71, -2.75, 29.4 ,  5.92,  0.08, 22.26, -8.89, 35.59,
       -9.74])

### Partie 3 – Exploration des tableaux

#### 1) Création aléatoire un tableau représentant les 24 températures d'une journée

In [14]:
np.random.seed(0)  # Pour la reproductibilité
temp_random_jours = np.random.uniform(-5.0, 45.0, 24).round(2)
temp_random_jours

array([22.44, 30.76, 25.14, 22.24, 16.18, 27.29, 16.88, 39.59, 43.18,
       14.17, 34.59, 21.44, 23.4 , 41.28, -1.45, -0.64, -3.99, 36.63,
       33.91, 38.5 , 43.93, 34.96, 18.07, 34.03])

#### 2) Détermination des propriétés suivantes du tableaux
        a) nombre de dimensions
        b) nombre de valeurs
        c) type des données
        d) forme du tableau

In [15]:
# Nombre de dimensions
dim = temp_random_jours.ndim
print("Nombre de dimensions :", dim)

Nombre de dimensions : 1


In [16]:
# nombre de valeurs dans le tableau
nb_valeurs = temp_random_jours.size
print("Nombre de valeurs :", nb_valeurs)

Nombre de valeurs : 24


In [17]:
# Type de données des éléments du tableau
type_donnees = temp_random_jours.dtype
print("Type de données :", type_donnees)

Type de données : float64


In [18]:
# Taille du tableau
taille = temp_random_jours.shape
print("Taille du tableau :", taille)


Taille du tableau : (24,)


### Partie 4 – Indexation et slicing 

Considérant le tableau représentant les 24 températures d'une journée, afficher : 

        1) la première mesure  ;  
        2) la dernière mesure ;  
        3) la température de 8h ;  
        4) les températures de 8h à 12h ;  
        5) les températures des 6 premières heures ;  
        6) les températures des heures paires.

#### 1) la première mesure

In [19]:
print("La première mesure est :", temp_random_jours[0])

La première mesure est : 22.44


#### 2) la dernière mesure

In [20]:
print("La dernière mesure est :", temp_random_jours[-1])

La dernière mesure est : 34.03


In [21]:
temp_random_jours

array([22.44, 30.76, 25.14, 22.24, 16.18, 27.29, 16.88, 39.59, 43.18,
       14.17, 34.59, 21.44, 23.4 , 41.28, -1.45, -0.64, -3.99, 36.63,
       33.91, 38.5 , 43.93, 34.96, 18.07, 34.03])

#### 3) la température de 8h

In [22]:
print("3) la température de 8h est :", temp_random_jours[8])

3) la température de 8h est : 43.18


#### 4) les températures de 8h à 12h

In [23]:
print("La température de 8h à 12h est :", temp_random_jours[8:13])

La température de 8h à 12h est : [43.18 14.17 34.59 21.44 23.4 ]


#### 5) les températures des 6 premières heures

In [24]:
print("La température des 6 premiers heures est :", temp_random_jours[:6])

La température des 6 premiers heures est : [22.44 30.76 25.14 22.24 16.18 27.29]


#### 6) les températures des heures paires

In [25]:
print("La température des heures pairs est :", temp_random_jours[::2])

La température des heures pairs est : [22.44 25.14 16.18 16.88 43.18 34.59 23.4  -1.45 -3.99 33.91 43.93 18.07]


### Partie 5 – Filtrage booléen

Considérant le tableau représentant les 24 températures d'une journée, on souhaite détecter les 
situations inhabituelles.  

#### 1) Affichage des températures supérieures à 30 °C

In [26]:
print("Les températures supérieures à 30°C sont :", temp_random_jours[temp_random_jours > 30])

Les températures supérieures à 30°C sont : [30.76 39.59 43.18 34.59 41.28 36.63 33.91 38.5  43.93 34.96 34.03]


#### 2) Afficher les températures « normales » càd comprises entre 20 °C et 30 °C 

In [27]:
masque = (temp_random_jours > 20) & (temp_random_jours < 30)
print("Les températures comprises entre 20°C et 30°C sont :", temp_random_jours[masque])

Les températures comprises entre 20°C et 30°C sont : [22.44 25.14 22.24 27.29 21.44 23.4 ]


3) Supposons qu'une température supérieure à 35 °C soit considérée comme anormale. 

Déterminons anomalies, un tableau de booléen précisant les anomalies

In [28]:
temp_random_jours

array([22.44, 30.76, 25.14, 22.24, 16.18, 27.29, 16.88, 39.59, 43.18,
       14.17, 34.59, 21.44, 23.4 , 41.28, -1.45, -0.64, -3.99, 36.63,
       33.91, 38.5 , 43.93, 34.96, 18.07, 34.03])

In [29]:
anomalies = temp_random_jours > 35
anomalies

array([False, False, False, False, False, False, False,  True,  True,
       False, False, False, False,  True, False, False, False,  True,
       False,  True,  True, False, False, False])

#### 4) Déterminons le nombre de températures anormales à l’aide de la variable anomalies  

In [30]:
print("Le nombre de mesures anormales est :", np.sum(anomalies))

Le nombre de mesures anormales est : 6


### Partie 6 – Manipulation des dimensions

On suppose qu’on a 5 capteurs. 

##### 1) Création aléatoire de la matrice représentant les températures mesurées par ces capteurs durant une journée 

In [32]:
np.random.seed(0)  # Pour la reproductibilité
temp_capteurs_jours = np.random.uniform(-5.0, 45.0, (5, 24)).round(2)
temp_capteurs_jours

array([[22.44, 30.76, 25.14, 22.24, 16.18, 27.29, 16.88, 39.59, 43.18,
        14.17, 34.59, 21.44, 23.4 , 41.28, -1.45, -0.64, -3.99, 36.63,
        33.91, 38.5 , 43.93, 34.96, 18.07, 34.03],
       [ 0.91, 27.  ,  2.17, 42.23, 21.09, 15.73,  8.23, 33.71, 17.81,
        23.42, -4.06, 25.88, 25.6 , 25.85, 42.19, 29.09, 12.98, 16.85,
        29.88, -1.99, 28.34, 28.53,  5.52,  1.45],
       [10.77, 13.19, 23.51, 16.93, 44.42,  0.1 ,  5.44,  3.07, 27.66,
         7.66, 18.32,  7.22,  2.95,  0.52, 27.82,  1.91,  4.83, 13.44,
        36.05, -0.14, 36.9 , -0.2 , 43.82, 18.43],
       [43.84, 25.24, 31.96, -3.04,  9.14,  1.01,  9.81,  0.94, 10.9 ,
        15.71, -1.79, 29.62, 23.33,  8.27, 21.16, -0.3 , 23.8 , 41.46,
        10.93, 28.37,  1.59, 30.82,  9.47,  4.16],
       [24.33, -3.99, 36.45, -4.77, 28.89,  8.5 , 31.76, 43.11,  7.44,
        23.81, 24.6 , 23.61,  6.15, 42.64, 17.36, 37.32, 29.97,  9.87,
        35.69, 14.83, 39.06, 24.06, 39.09, 29.63]])

#### 2) Transformation de la matrice en un tableau unidimensionnel 

In [34]:
# Transformation de la matrice en un tableau unidimensionnel
temp_capteurs_jours_flat = temp_capteurs_jours.flatten()
temp_capteurs_jours_flat.shape      # Pour vérifier la nouvelle forme du tableau

(120,)

#### 3) Déterminons la transposée de la matrice 

In [35]:
temp_capteurs_jours_trans = temp_capteurs_jours.T
temp_capteurs_jours_trans.shape      # Pour vérifier la nouvelle forme du tableau

(24, 5)

#### 4) Extraction de toutes les mesures du capteur 1

In [36]:
# Extraction de toutes les mesures du capteur 1
capteur_1 = temp_capteurs_jours[0, :]
capteur_1

array([22.44, 30.76, 25.14, 22.24, 16.18, 27.29, 16.88, 39.59, 43.18,
       14.17, 34.59, 21.44, 23.4 , 41.28, -1.45, -0.64, -3.99, 36.63,
       33.91, 38.5 , 43.93, 34.96, 18.07, 34.03])

#### 5) Extraction toutes les mesures du capteur 5

In [39]:
# Extraction toutes les mesures du capteur 5
capteur_5 = temp_capteurs_jours[4, :]
capteur_5

array([24.33, -3.99, 36.45, -4.77, 28.89,  8.5 , 31.76, 43.11,  7.44,
       23.81, 24.6 , 23.61,  6.15, 42.64, 17.36, 37.32, 29.97,  9.87,
       35.69, 14.83, 39.06, 24.06, 39.09, 29.63])

#### 6) Extraction des mesures de tous les capteurs à 10h

In [41]:
# Extraction des mesures de tous les capteurs à 10h
mesures_10h = temp_capteurs_jours[:, 10]
mesures_10h

array([34.59, -4.06, 18.32, -1.79, 24.6 ])

#### 7) Extraction des mesures des capteurs 2 à 4 entre 8h et 12h

In [42]:
# Extraction des mesures des capteurs 2 à 4 entre 8h et 12h
mesures_interval_812 = temp_capteurs_jours[1:4, 8:12]
mesures_interval_812

array([[17.81, 23.42, -4.06, 25.88],
       [27.66,  7.66, 18.32,  7.22],
       [10.9 , 15.71, -1.79, 29.62]])