## Atelier Numpy

### Contexte 
Une entreprise dispose de plusieurs capteurs installés dans différents bâtiments. Les capteurs 
mesurent régulièrement la température, l'humidité, la pression et la consommation énergétique. 
Les données doivent être préparées et analysées avant d'être transmises à un futur système de 
Machine Learning permettant de détecter des situations anormales 

### Partie 1 : Listes Python vs tableaux NumPy 

On dispose des températures mesurées par un capteur : 24.5, 25.1, 26.3, 27.0 et 25.8 

#### 1) Créer une liste Python stockant ces températures

In [4]:
tprt = [24.5, 25.1, 26.3, 27.0, 25.8]

#### 2) Création d'un tableau NumPy équivalent stockant ces températures

In [1]:
# Importation de la bibliothèque NumPy
import numpy as np

In [2]:
tprt_array = np.array([24.5, 25.1, 26.3, 27.0, 25.8])

#### 3) Multiplication par 2 sur ces deux collections

In [5]:
# Multiplication de chaque élément de la liste par 2
mul_tprt_list = [temp * 2 for temp in tprt]
mul_tprt_list

[49.0, 50.2, 52.6, 54.0, 51.6]

In [6]:
# Multiplication de chaque élément du tableau NumPy par 2
mul_tprt_array = tprt_array * 2
mul_tprt_array

array([49. , 50.2, 52.6, 54. , 51.6])

#### 4) Différence observée ?

On remarque que le liste python 'tprt' utilise une boucle 'for' en multipliant chaque élément de la liste pour pouvoir
avoir le résulat de la multiplication par 2 des températures stockés. Par contre le vecteur Numpy 'tprt_array' multiplie directement et simultanément tous éléments par 2 (technique du 'broadcasting') sans passer par une boucle. Ce qui énorme un terme de gain de temps 

### Partie 2 – Création des données

#### 1) Création d'un tableau représentant les mesures de température de 10 capteurs, initialement à zéro.

In [9]:
temp_10 = np.zeros(10)
temp_10

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 2) Création d'un tableau contenant 10 valeurs égales à 1

In [10]:
temp_10_1 = np.ones(10)
temp_10_1

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 3) Création d'un tableau de 10 valeurs initialisées à 25

In [11]:
temp_10_25 = np.full(10, 25)
temp_10_25

array([25, 25, 25, 25, 25, 25, 25, 25, 25, 25])

#### 4) Création une matrice identité de taille 5 × 5

In [12]:
temp_ident = np.eye(5)
temp_ident

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### 5) Création de 24 heures (de 0 à 23) de mesure d’une journée 

In [13]:
temp_24 = np.arange(24)
temp_24

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

#### 6) Création de 10 valeurs régulièrement réparties entre 20 °C et 30 °C 

In [14]:
temp10_20_30 = np.linspace(20, 30, 10)
temp10_20_30

array([20.        , 21.11111111, 22.22222222, 23.33333333, 24.44444444,
       25.55555556, 26.66666667, 27.77777778, 28.88888889, 30.        ])

#### 7) Création aléatoire de températures de 100 mesures, en rendant les résultats reproductibles

In [52]:
np.random.seed(0)  # Pour la reproductibilité
temp_random = np.random.uniform(-10.0, 45.0, 100).round(2)
temp_random

array([20.18, 29.34, 23.15, 19.97, 13.3 , 25.52, 14.07, 39.05, 43.  ,
       11.09, 33.54, 19.09, 21.24, 40.91, -6.09, -5.21, -8.89, 35.79,
       32.8 , 37.85, 43.82, 33.95, 15.38, 32.93, -3.49, 25.2 , -2.12,
       41.96, 18.7 , 12.81,  4.55, 32.58, 15.09, 21.26, -8.97, 23.97,
       23.67, 23.93, 41.91, 27.5 ,  9.77, 14.04, 28.37, -6.69, 26.67,
       26.89,  1.57, -2.91,  7.35, 10.  , 21.36, 14.12, 44.36, -4.39,
        1.49, -1.13, 25.92,  3.93, 15.65,  3.44, -1.26, -3.93, 26.1 ,
       -2.4 ,  0.81, 10.28, 35.15, -4.66, 36.09, -4.71, 43.71, 15.78,
       43.72, 23.27, 30.66, -7.84,  5.55, -3.39,  6.29, -3.47,  7.49,
       12.78, -6.47, 28.09, 21.16,  4.6 , 18.78, -4.83, 21.68, 41.11,
        7.52, 26.71, -2.75, 29.4 ,  5.92,  0.08, 22.26, -8.89, 35.59,
       -9.74])

### Partie 3 – Exploration des tableaux

#### 1) Création aléatoire un tableau représentant les 24 températures d'une journée

In [53]:
np.random.seed(0)  # Pour la reproductibilité
temp_random = np.random.uniform(-5.0, 45.0, 24).round(2)
temp_random

array([22.44, 30.76, 25.14, 22.24, 16.18, 27.29, 16.88, 39.59, 43.18,
       14.17, 34.59, 21.44, 23.4 , 41.28, -1.45, -0.64, -3.99, 36.63,
       33.91, 38.5 , 43.93, 34.96, 18.07, 34.03])